install:
	# Have to install with yarn over npm due to issues with detect-port
	# https://github.com/node-modules/detect-port/issues/31
	yarn install

build: install
	npm run build

run: install
	npm run start
