runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /static
  static_dir: app/static
- url: /images
  static_dir: app/images
- url: /asset-manifest.json
  static_files: app/asset-manifest.json
  upload: app/asset-manifest.json
- url: /logo.png
  static_files: app/logo.png
  upload: app/logo.png
- url: /manifest.json
  static_files: app/manifest.json
  upload: app/manifest.json
- url: /service-worker.js
  static_files: app/service-worker.js
  upload: app/service-worker.js
- url: /(.*\.pdf)$
  static_files: app/pdf/\1
  upload: app/pdf/.*\.pdf$
- url: /(about|gallery|events|stockists|videos)
  static_files: app/index.html
  upload: app/index.html
  expiration: 1m
- url: /
  static_files: app/index.html
  upload: app/index.html
  expiration: 1m
